"""Lakebase Postgres helpers for the capstone app.

All in-app DB reads/writes run as the app service principal (Lakebase
doesn't yet support OBO scopes). The calling user is recorded
separately in ``customer_audit_log.actor`` via ``X-Forwarded-Email``;
see ``auth.caller_email``.

Postgres OAuth tokens minted by ``generate_database_credential`` are
short-lived (~1h). The simplest way to never get burned by expiry is
to mint a fresh credential per checkout — that's what ``lakebase_sp``
does. Connection pooling with background token rotation is also
viable; per-checkout was chosen here for clarity.
"""

from __future__ import annotations

import os
from contextlib import contextmanager
from typing import Iterator

import psycopg

from .auth import sp_client


def _pg_config() -> dict[str, str]:
    """Read Postgres connection params from env. Fail loudly if missing."""
    try:
        return {
            "host":     os.environ["PGHOST"],
            "db":       os.environ["PGDATABASE"],
            "instance": os.environ.get("PG_INSTANCE_NAME", "capstone-pg"),
        }
    except KeyError as e:
        raise RuntimeError(
            f"Missing required env var {e!s}. Expected PGHOST, PGDATABASE, "
            "PG_INSTANCE_NAME — generated by the installer into app/.env."
        ) from e


def _fresh_credential(instance: str) -> tuple[str, str]:
    """Mint a Lakebase OAuth credential for the app SP.

    Returns ``(username, token)``. The username is the SP's identity
    (the Postgres role created when the instance was provisioned);
    the token is the password.
    """
    w = sp_client()
    cred = w.database.generate_database_credential(
        request_id="capstone-app",
        instance_names=[instance],
    )
    return w.current_user.me().user_name, cred.token


@contextmanager
def lakebase_sp() -> Iterator[psycopg.Connection]:
    """Yield a psycopg connection authenticated as the app SP.

        with lakebase_sp() as conn, conn.cursor() as cur:
            cur.execute("SELECT 1")

    A fresh OAuth credential is minted on entry, so callers never see
    token-expiry errors. The connection is closed on exit; commit
    yourself before leaving the ``with`` block (or use
    ``conn.autocommit = True``) — psycopg does not implicitly commit
    on close.
    """
    cfg = _pg_config()
    user, token = _fresh_credential(cfg["instance"])
    conn = psycopg.connect(
        host     = cfg["host"],
        port     = 5432,
        dbname   = cfg["db"],
        user     = user,
        password = token,
        sslmode  = "require",
    )
    try:
        yield conn
    finally:
        conn.close()
